### ISSUE TITLE
bgp.config not working with iosxr driver

### ISSUE THREAD

**Issue by wasabi222** [napalm-automation/napalm-salt#21] opened 2016-12-29 15:31 UTC
output of command:

>>> root# salt gw.domain bgp.config
gw.domain:
    ----------
    comment:
        Cannot execute "get_bgp_config" on gw.domain as user. Reason: 'NoneType' object has no attribute 'lower'!
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/var/cache/salt/minion/extmods/proxy/napalm.py", line 284, in call
            out = getattr(NETWORK_DEVICE.get('DRIVER'), method)(**params)  # calls the method with the specified parameters
          File "/usr/local/lib/python2.7/site-packages/napalm_iosxr/iosxr.py", line 706, in get_bgp_config
            result_tree = ETREE.fromstring(self.device.make_rpc_call(rpc_command))
        AttributeError: 'NoneType' object has no attribute 'lower'

The get_bgp_config method does work with the iosxr driver, just not with this salt module.

>>> gw.get_bgp_config()
(working output here)

iosxr version: 5.3.3 sp4
salt version: salt 2016.11.1 (Carbon)

**Comment by mirceaulinic** [comment] 2017-01-30 16:54
This was fixed in https://github.com/saltstack/salt/pull/38499/files

**Comment by mirceaulinic** [comment] 2017-01-30 23:46
`2016.11.2` has been released: https://docs.saltstack.com/en/latest/topics/releases/2016.11.2.html and contains that fix.
I will close this issue for now. If the issue isn't resolved drop a comment here and I can reopen it.

**Closed as completed by mirceaulinic** 2017-01-30 23:46 UTC
Labels: bug
