### ISSUE TITLE
Cisco device error in the log

### ISSUE THREAD

**Issue by AmbicaY** [napalm-automation/napalm-salt#49] opened 2018-05-16 13:09 UTC
I see this error continuously logged in my proxy minion for cisco device:
Exception argument of type 'bool' is not iterable occurred in scheduled job

Any idea about this error?

**Comment by mirceaulinic** [comment] 2018-05-21 08:43
Closing, as it's a duplicate of https://github.com/saltstack/salt/issues/47695.

**Closed as completed by mirceaulinic** 2018-05-21 08:43 UTC
Labels: bug, duplicate
